config/routes.rb
TaskManager::Application.routes.draw do
  get "tasks/create"
  get "tasks/destroy"
  devise_for :users
  resources :projects do
    collection do
      post "task_state_change" => 'tasks#change', as: :task_state_change
    end
    resources :tasks do
      member do
        post "increase_priority"
        post "decrease_priority"        
      end
    end  
  end

   root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  belongs_to :user
  validates :name, presence: true, length: { in: 4..50 }, uniqueness: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  validates :name, presence: true, length: { in: 1..100 }
  validates :priority, numericality: { only_integer: true }
  before_create :set_priority
  before_destroy :shift_priority

  def set_priority
    self.priority = project.tasks.count
  end

  def up
    unless self.priority == 0 
      task_down = project.tasks.where(priority: priority - 1).first
      self.priority -= 1
      task_down.priority += 1
      self.save and task_down.save
    end
  end

  def down
    unless self.priority == project.tasks.count - 1  
      task_up = project.tasks.where(priority: priority + 1).first
      self.priority += 1
      task_up.priority -= 1
      self.save and task_up.save
    end
  end

  def shift_priority
    project.tasks.where('priority > ?',  priority).each do |task|
      task.priority -= 1
      task.save
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!


  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.where( user: current_user )
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user = current_user
    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_path }
        format.json { head :no_content }
      else
        flash[:alert] = @project.errors.full_messages
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.projects.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :set_project, except: :change
  before_filter :set_task, only: [:edit, :update, :increase_priority, :decrease_priority]
  before_filter :authenticate_user!  


  def create
    @task = @project.tasks.build(task_params)
    flash[:alert] = @task.errors.full_messages unless @task.save
    redirect_to root_path
  end

  def edit
  end

  #changes task name
  def update 
    if @task.update(task_params)
      redirect_to projects_path
    else
      flash[:alert] = @task.errors.full_messages
      render action: 'edit'
    end
  end

  #change status: completed/not completed
  def change
    task = Task.find(params[:id])
    task.completed = params[:state]
    task.save
    render :json => { status: 200 }
  end

  def destroy
    @project.tasks.find(params[:id]).destroy
    render :json => { status: 200 }
  end

  def increase_priority
    @task.up
    redirect_to projects_path
  end

  def decrease_priority  
    @task.down
    redirect_to projects_path    
  end

private
  def set_project
    @project = current_user.projects.find(params[:project_id])
  end

  def set_task
    @task = @project.tasks.find(params[:id])
  end

  def task_params
    params[:task].permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_footer.html.erb
<div class="bs-component">  
  <div class="navbar-text space" id="created_for">
    <a href='http://rubygarage.org' target="_blank" >Created for rubygarage.org</a>      
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="bs-component">  
  <div class="navbar navbar-inverse">
    <div class="navbar-header">
      <a href=<%=root_path%> class="navbar-brand">Task Manager</a>
    </div>
    <div class="navbar-collapse collapse navbar-inverse-collapse">
      <ul class="nav navbar-nav navbar-right">    
        <%- if user_signed_in? %>
          <li><a href=<%=edit_user_registration_path%>> <%=current_user.email%></a></li> 
          <li><%= link_to 'Sign out', destroy_user_session_path, :method => 'delete' %></li>
        <% else %>
          <%- if current_page? new_user_registration_path %>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
          <%- else %>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>          
          <% end %>  
        <% end %>        
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body  class="my_html">
    <%= render 'layouts/header' %>
    <%- if !notice.nil? && !notice.empty? %>
   	  <p class="notice" id="notice"><%= notice %></p>
    <% end %>
    <%- if !alert.nil? && !alert.empty? %>
      <p class="alert alert-danger"><%= alert %></p>  
    <% end -%>  
    
    <%= yield %>
    
    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => "control-label" %>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="form-group text-center">
    <%= link_to "Back", :back, :class => "btn btn-link" %>
    <%= f.submit "Save", :type => "submit", :class => "btn btn-primary" %>    
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class=" text-center">
  <div class="page-header">  
    <h1>Editing project</h1>
  </div>
</div>

<div class="form_wrap center">
  <%= render 'form' %>
</div>

app/views/projects/index.html.erb
<div id="projects-wrap" class="center">
  <div class="page-header">
    <h1 class="text-center">Listing projects</h1>
  </div>
  <% @projects.each do |project| %>
    <div class="panel panel-info">
      <div class="panel-heading" >
        <div class="panel-title">
          <%= project.name %>
          <div class="float-right">
            <%= link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe, edit_project_path(project) %>
            <%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, project, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      </div>
      <div class="panel-body light-blue-background padding-margin-nil">
          <%= form_for [project, project.tasks.build] do |f| %>        
        <div class="input-group">
          <span class="input-group-addon">
            <span class="glyphicon glyphicon-plus green"></span>
          </span>
          <%= f.text_field :name, placeholder: 'Please enter your task here', :class => "form-control" %>          
          <span class="input-group-btn light-blue-background">
            <%= f.submit 'Add Task', :class => "btn btn-info" %>
          </span>
        </div>
          <% end %>        
        <table class="table table-hover padding-margin-nil" id="table-tasks">
          <tbody>
            <%- project.tasks.sort_by(&:priority).each do |task| %>
              <% unless task.name.nil? %>
                <tr>
                  <td class="width5">
                    <input class="completed-checkbox" data-id="<%= task.id %>" type="checkbox" autocomplete="off" <%= 'checked' if task.completed? %> >
                  </td>
                  <td><%= task.name %></td>
                  <td class="width10" id="task-edit">                
                    <%= link_to '<span class="glyphicon glyphicon-arrow-up"></span>'.html_safe, increase_priority_project_task_path(project, task), method: :post %>         
                    <%= link_to '<span class="glyphicon glyphicon-arrow-down"></span>'.html_safe, decrease_priority_project_task_path(project, task), method: :post %>
                    <%= link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe, edit_project_task_path(project, task) %>
                    <%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, [project, task], method: :delete, data: { confirm: 'Are you sure?' },
                                                                                                                  remote: true, :class => "link_to_delete_task" %>
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>          
      </div>
    </div>
  <% end %>
  <div class="text-center">
    <%= link_to 'Create Project', new_project_path, :class => "btn btn-link" %>
  </div>
</div>

app/views/projects/new.html.erb
<div class=" text-center">
  <div class="page-header">  
    <h1>New project</h1>
  </div>
</div>

<div class="form_wrap center">
  <%= render 'form' %>
</div>

app/views/projects/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/tasks/edit.html.erb
<div class="form_wrap center">

  <%= form_for @task, url: "/projects/#{@project.id}/tasks/#{@task.id}", method: :patch do |f| %>

    <% if @task.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

        <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, :class => "control-label" %>
      <%= f.text_field :name, :class => "form-control" %>
    </div>
    <div class="form-group text-center">
      <%= link_to "Back", :back, :class => "btn btn-link" %>
      <%= f.submit "Save", :type => "submit", :class => "btn btn-primary" %>    
    </div>

  <% end %>
</div>    